image: "python:3.7"

#cache:
#  key:
#    files:
#      - poetry.lock
#    prefix: "${CI_JOB_NAME}"
#  paths:
#    - .venv

stages:
  - tests
  - docs
  - build-docker

.install-deps-template: &install-deps
  before_script:
    - pip install --upgrade pip virtualenv
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry --version
    # Force a recent pip version inside the virtualenv
    - virtualenv .venv
    - .venv/bin/pip install --upgrade pip
    - poetry config virtualenvs.in-project true
    - poetry install -E all

.test-template: &test
  <<: *install-deps
  stage: tests
  coverage: '/TOTAL.*\s(\d+\.\d+\%)/'
  script: poetry run pytest -v

python3.6:
  <<: *test
  image: python:3.6

python3.7:
  <<: *test
  image: python:3.7

python3.8:
  <<: *test
  image: python:3.8

docs:
  <<: *install-deps
  stage: docs
  needs: ['python3.8']
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  script:
    - . .venv/bin/activate
    - cd docs
    - make html
    - cd _build/html
    # https://about.gitlab.com/blog/2017/11/02/automating-boring-git-operations-gitlab-ci/
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - git config --global user.name "bio_embeddings"
    - git config --global user.email "support@bioembeddings.com"
    - git init
    - git add .
    - git commit -m 'Upload docs'
    # https://stackoverflow.com/a/29380765/3549270
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git remote add origin git@github.com:sacdallago/bio_embeddings.git
    - git push -f origin master:gh-pages

build-webserver:
  stage: build-docker
  needs: ['python3.8']
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/webserver/Dockerfile.webserver --destination ghcr.io/bioembeddings/webserver

build-worker:
  stage: build-docker
  needs: ['python3.8']
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/webserver/Dockerfile.worker --destination ghcr.io/bioembeddings/worker
