global:
  sequences_file: disordercdhit.fasta
  prefix: disprot
seqvec_embeddings:
  type: embed
  protocol: seqvec
  reduce: True
  weights_file: /mnt/nfs/models/seqvec/weights_file
  options_file: /mnt/nfs/models/seqvec/options_file
  max_amino_acids: 17000
umap_projections:
  type: project
  protocol: umap
  depends_on: seqvec_embeddings
plotly_visualization:
  type: visualize
  protocol: plotly
  annotation_file: disprot_2019_09_labelled_0.2_0.8.csv
  display_unknown: False
  depends_on: umap_projections
