global:
  sequences_file: cath-domain-seqs-S35.fa
  prefix: cath
  simple_remapping: True
seqvec_embeddings:
  type: embed
  protocol: seqvec
  reduce: True
umap_projections:
  type: project
  protocol: umap
  depends_on: seqvec_embeddings
  n_components: 2
plotly_visualization:
  type: visualize
  protocol: plotly
  annotation_file: cath_classes_S35.csv
  depends_on: umap_projections
