global:
  sequences_file: sequences.fasta
  prefix: mmseqs_simple
mmseqs2_alignment:
  type: align
  protocol: mmseqs_search
  search_sequences_file: deeploc_data.fasta
  mmseqs_search_options:
    num_iterations: 5
    alignment_output: True
