# Max content length determines the maximum size of files to be uploaded: 16 * 1024 * 1024 = 16MB
max_content_length: 16 * 1024 * 1024

# CORS origins
origins:
  - https://embed.protein.properties
  - http://localhost:3000


# Max allowed AA in submission
max_allowed_aa: 15000