version: '3.1'

services:
  mongo:
    image: mongo:4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - bio_embeddings

  rabbitmq:
    image: rabbitmq:3-alpine
    hostname: bio_embeddings_host
    container_name: rabbitmq
    networks:
      - bio_embeddings

  bio_embeddings_worker:
    image: ghcr.io/bioembeddings/worker
    container_name: bio_embeddings_worker
    volumes:
      - /mnt/nfs/models:/mnt/models
    environment:
      CELERY_BROKER_URL: amqp://rabbitmq
      MONGO_URL: mongodb://root:example@mongo:27017
    networks:
      - bio_embeddings

  bio_embeddings_webserver:
    image: ghcr.io/bioembeddings/webserver
    container_name: bio_embeddings_webserver
    ports:
      - 3000:3000
    environment:
      CELERY_BROKER_URL: amqp://rabbitmq
      MONGO_URL: mongodb://root:example@mongo:27017
    networks:
      - bio_embeddings

networks:
  bio_embeddings: