global:
  sequences_file: https://raw.githubusercontent.com/sacdallago/bio_embeddings/develop/examples/use_case_one/fasta.fa
  prefix: simple
bert_embeddings:
  type: embed
  protocol: prottrans_bert_bfd
  reduce: True
tsne_projections:
  type: project
  protocol: tsne
  depends_on: bert_embeddings
plotly_visualization:
  type: visualize
  protocol: plotly
  depends_on: tsne_projections
  annotation_file: https://raw.githubusercontent.com/sacdallago/bio_embeddings/develop/examples/use_case_one/annotation_file.csv
