global:
  sequences_file: fasta.fa
  prefix: simple
seqvec_embeddings:
  type: embed
  protocol: seqvec
  weights_file: /Users/chdallago/git/api.embed.protein.properties/models/seqvec/weights_file
  options_file: /Users/chdallago/git/api.embed.protein.properties/models/seqvec/options_file
features_from_seqvec:
  type: extract
  protocol: seqvec_from_publication
  depends_on: seqvec_embeddings