global:
  sequences_file: fasta.fa
  prefix: simple
albert_embeddings:
  type: embed
  protocol: albert
  reduce: True
tsne_projections:
  type: project
  protocol: tsne
  depends_on: albert_embeddings
plotly_visualization:
  type: visualize
  protocol: plotly
  depends_on: tsne_projections
  annotation_file: annotation_file.csv